### PR TITLE
update to latest JOSM, cleanup

### PR DESCRIPTION
**Pull request by don-vip**

### CODE REVIEW

**Comment by andreimaneasa** [comment]
Hi, do you want to modify something else, or I can merge this branch?

**Comment by don-vip** [comment]
you can merge it :)

**Comment by don-vip** [comment]
thanks! can you please now recompile the plugin and publish a new release? We have new bug reports, see https://josm.openstreetmap.de/ticket/13606

**Comment by don-vip** [comment]
Hi Andrei,
Can you please publish a new release?

**Comment by don-vip** [comment]
Hi Andrei,
Would you be ok to transfer the repository to @JOSM organization so we can maintain the plugin?

**Comment by andreimaneasa** [comment]
Hi, of course. Sorry for the delay. Would be better for JOSM community. For the moment I haven't the necessary time to improve it. So please transfer the repository and feel free to do what you want ;) Thanks

**Comment by don-vip** [comment]
I cannot transfer it, only you have this possibility. Can you please accept my invitation request to https://github.com/orgs/JOSM/teams/color then transfer the repository to the @JOSM organization? After that we will be able to maintain the plugin :)

**Comment by andreimaneasa** [comment]
I can't access the invitation link... :-|

I found it :+1:

**Comment by andreimaneasa** [comment]
Hey, I created a new repository called "ColorPlugin". Enjoy it :smile:

**Pull request merged**
